# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  set_build_tag:
    name: Set build tag
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        id: current_time
        run: echo "::set-output name=time::$(date +'%Y%m%d%H%M')"
      - name: Get short SHA
        id: short_sha
        run: |
          sha=$(echo ${{github.sha}} | cut -c1-7)
          echo "::set-output name=sha::$sha"
      - name: Set build tag
        run: echo "BUILD_TAG=${{ steps.current_time.outputs.time }}-${{ steps.short_sha.outputs.sha }}" >> $GITHUB_ENV
      - name: Save build tag
        run: echo ${{ env.BUILD_TAG }} > build-tag.txt
      - name: Upload build tag
        uses: actions/upload-artifact@v2
        with:
          name: mytestartifact
          path: build-tag.txt
      - name: Sleep a bit
        run: |
          echo "Going to sleep..."
          sleep 120
          echo "Waking up..."
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [set_build_tag]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: show env
        run: env

      - name: show github_run_id
        run: echo $GITHUB_RUN_ID

      - name: list artifacts from the running workflow 
        run: |
          echo $GITHUB_RUN_ID
          curl \
          -H "Accept: application/vnd.github.v3+json" \
          -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/bas/gha-artifact-api-test/actions/runs/$GITHUB_RUN_ID/artifacts

      - name: list artifacts from a previous pipeline
        run: |
          curl \
          -H "Accept: application/vnd.github.v3+json" \
          -H "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/bas/gha-artifact-api-test/actions/runs/1777893368/artifacts

      - name: Download artifact with github action
        uses: actions/download-artifact@v2
        with:
          name: mytestartifact
